### ISSUE TITLE
PVC not build on Open Shift

### ISSUE THREAD

**Issue by DaBeIDS** [os-climate/corporate_data_extraction#7]
Hi, 
we wanted to build a Persistent Volume Claim on open shift in the aicos-osc-demo project:

![image](https://github.com/os-climate/corporate_data_extraction/assets/90916810/ed05a4c4-8d0b-408b-8999-12f1f91fd481)

But it is still pending since monday (2 days). Is that normal or is there a restriction?

Reason is that we wanted to test the extraction code and for that we need a storage which our four pods can share:

![image](https://github.com/os-climate/corporate_data_extraction/assets/90916810/b94ffbfd-f1db-40e1-a487-964a71be0fa6)

Let me know if there is another way to do so.

Thanks,

David

**Comment by redmikhail** [comment]
Hi @DaBeIDS , it seems that PVC is in "waiting for first consumer to be created before binding" state . (You can always check Events tab in Observe to see what events are being generated) Ultimately PVC will be created when it referenced somewhere in the pod (Volume and Volume mounts in https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-pod). Which pod/deployment you were planning to use it in ?

**Comment by DaBeIDS** [comment]
Hi @redmikhail, ok thanks for the info. I thought exactly the other way round. I thought i can not connect before it is not build :). I wanted to use the PVC to connect with all pods in the application "corporate-data-extraction-full-pipeline" to it. Because the pod "main-terminal" triggers jobs in the others and the output needs then to be moved to the next pod. To ensure that this is possible i wanted to use the PVC. I will check your link to understand how to do it.
Thanks!

**Comment by redmikhail** [comment]
@DaBeIDS makes sense. However most common use of PVC and PV (persistent volume) is to have PVC associated only with one pod (you will get message that pvc is already in use when you try to define PVC reference from second pod) , RWO PV in https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes. While Kubernetes supports so called RWX PV that allow multiple pods to write to the same storage, underlying physical infrastructure needs to be able to handle it . We currently have only gp2/gp3 storage classes in our Openshift cluster both both do not supporting RWX. Additionally it is generally not consider to be good pattern for containerized workload to use shared filesystem . I would recommend to see if S3 object storage can be used from pipeline code instead . We can provision S3 bucket specific for this purposes and it can work perfectly fine with multiple pods accessing it . Please let me know if it is something possible to use , otherwise we can try to figure out something else.

**Comment by DaBeIDS** [comment]
@redmikhail Thanks for you detailed explanation. We are currently thinking about different solutions here, but S3 seems to be the better solution then. Could you provision S3 bucket to us for this purpose with the above mentioned purpose? 
The code itself needs that we have a "project folder" with a name like "ESG" or "TEST" and then inside of that folder the structure needs to be input, interim, output. So, i guess the S3 bucket would be a layer on top of the project folder level.
But it would be nice if we could set up the inner structure on our own to ensure that everything is as expected. Unfortunately i never used S3 buckets directly before, but i hope what i described is possible. :)

**Comment by DaBeIDS** [comment]
We are now using S3 as a connection platform (a main and an interim bucket) and added PVC to all deployments. This works.
